# Generated by packaging/homebrew/generate-formula.sh — do not edit by hand.
class LastpassSshAgent < Formula
  desc "SSH agent backed by the LastPass CLI: keys never persist on disk"
  homepage "https://github.com/lexbrugman/lastpass-ssh-agent"
  version "2026.811.0"
  license "MIT"

  depends_on "lastpass-cli"

  # The dev track. `brew install --HEAD` builds the dev branch from source,
  # which is why rust is a build dependency here and nowhere else: a release
  # install unpacks a prebuilt binary and needs no compiler.
  head do
    url "https://github.com/lexbrugman/lastpass-ssh-agent.git", branch: "dev"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.811.0/lastpass-ssh-agent-aarch64-apple-darwin.tar.xz"
      sha256 "b4cd62244c382d1a20e9c761ec21be360a03d87df581abcca9100187561a36ff"
    end
    on_intel do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.811.0/lastpass-ssh-agent-x86_64-apple-darwin.tar.xz"
      sha256 "ac0be74baec1863c74a325694dd50a55a19aabcb1d65962c7192ad763a27a81b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.811.0/lastpass-ssh-agent-aarch64-unknown-linux-musl.tar.xz"
      sha256 "45eb4971b8fadd536a0092a7609f91ccdf127954fb80f3fb81d2de26adaab8c4"
    end
    on_intel do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.811.0/lastpass-ssh-agent-x86_64-unknown-linux-musl.tar.xz"
      sha256 "7ad2cc7fea4d45595528022533da3c4c7d5953d5e042e1a304b945f366b73a53"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "lastpass-ssh-agent"
    end
  end

  # `brew services start lastpass-ssh-agent` installs this as a launchd user
  # agent on macOS and a systemd user unit on Linux — same declaration, both
  # platforms. std_service_path_env puts Homebrew's bin on PATH so the agent
  # can find lpass, which a bare launchd/systemd environment would not.
  service do
    run [opt_bin/"lastpass-ssh-agent", "start"]
    keep_alive true
    log_path var/"log/lastpass-ssh-agent.log"
    error_log_path var/"log/lastpass-ssh-agent.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      Log in to LastPass first, then check the setup:

        lpass login you@example.com
        lastpass-ssh-agent doctor

      Run it in the background (launchd on macOS, systemd --user on Linux):

        brew services start lastpass-ssh-agent

      It then starts again at every login. Homebrew does not restart running
      services on upgrade, so after `brew upgrade` the old binary keeps
      serving until the next login unless you restart it yourself:

        brew services restart lastpass-ssh-agent

      On Linux a --user service only runs while you have a session. To keep
      the agent up without one:

        loginctl enable-linger "$USER"

      Do NOT use `sudo brew services`: as a system daemon the agent has no
      GUI session, so every confirmation prompt fails closed and no signature
      is ever approved.

      On Linux the default confirmation mode is "tty", which a background
      service has no terminal for. Set an askpass helper in
      ~/.config/lastpass-ssh-agent/config.toml before starting the service:

        confirm = "askpass"
        askpass = "/usr/bin/ssh-askpass"

      Point SSH at the agent. The socket path differs per platform, so take
      it from the agent rather than guessing:

        lastpass-ssh-agent env

      and put that path in ~/.ssh/config:

        Host *
            IdentityAgent "<the path printed above>"

      Note that IdentityAgent overrides SSH_AUTH_SOCK for the hosts it matches.

      To follow the dev branch instead of releases, replace the install. It
      builds from source, so this pulls in a Rust toolchain:

        brew uninstall lastpass-ssh-agent
        brew install --HEAD lastpass-ssh-agent

      Switching tracks is always uninstall-then-install: `brew reinstall` has
      no --HEAD option, and cannot move an install between the two.

      A HEAD install does NOT move forward on a plain `brew upgrade` — brew
      only checks whether the branch advanced when asked to:

        brew upgrade --fetch-HEAD lastpass-ssh-agent

      And back to the latest release:

        brew uninstall lastpass-ssh-agent
        brew install lastpass-ssh-agent

      Either switch replaces the binary, not the running agent, so restart the
      service afterwards. Saved Keychain passphrases are keyed by SSH key
      fingerprint and survive the switch.
    EOS
  end

  test do
    # A release install must report exactly the version the formula claims —
    # a mismatch there means the formula and the binary came from different
    # builds. A head install cannot: brew calls it HEAD-<sha> while the binary
    # describes itself against the newest release tag it can see, so check the
    # name instead. Decided from `version` rather than `build`, which is not
    # dependable in a test.
    expected = if version.to_s.start_with?("HEAD")
      "lastpass-ssh-agent"
    else
      version.to_s
    end
    assert_match expected, shell_output("#{bin}/lastpass-ssh-agent --version")
    # doctor exits nonzero without a LastPass login, but must still run
    assert_match "lpass", shell_output("#{bin}/lastpass-ssh-agent doctor 2>&1", 1)
  end
end
