# Generated by packaging/homebrew/generate-formula.sh — do not edit by hand.
class LastpassSshAgent < Formula
  desc "SSH agent backed by the LastPass CLI: keys never persist on disk"
  homepage "https://github.com/lexbrugman/lastpass-ssh-agent"
  version "2026.825.0"
  license "MIT"

  depends_on "lastpass-cli"

  # The dev track. `brew install --HEAD` builds the dev branch from source,
  # which is why rust is a build dependency here and nowhere else: a release
  # install unpacks a prebuilt binary and needs no compiler.
  head do
    url "https://github.com/lexbrugman/lastpass-ssh-agent.git", branch: "dev"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.825.0/lastpass-ssh-agent-aarch64-apple-darwin.tar.xz"
      sha256 "746ab4d6500ebb1a84443a09f76898bbcf6f662cd41452e2c7d63f904de84b5c"
    end
    on_intel do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.825.0/lastpass-ssh-agent-x86_64-apple-darwin.tar.xz"
      sha256 "22b06e2b3afd1210d4f74575bf6da99657f9b2e62b77f8c05cb4f9c736224c1f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.825.0/lastpass-ssh-agent-aarch64-unknown-linux-musl.tar.xz"
      sha256 "2e01ccb06c77964765d05adf4ed150751054b312c96b3d5f03de181eedacfa98"
    end
    on_intel do
      url "https://github.com/lexbrugman/lastpass-ssh-agent/releases/download/v2026.825.0/lastpass-ssh-agent-x86_64-unknown-linux-musl.tar.xz"
      sha256 "db98cb58157b7d219ac085695c648ab5db339ab0dbb67fd586163df139b5e526"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "lastpass-ssh-agent"
    end
  end

  # `brew services start lastpass-ssh-agent` installs this as a launchd user
  # agent on macOS and a systemd user unit on Linux — same declaration, both
  # platforms. std_service_path_env puts Homebrew's bin on PATH so the agent
  # can find lpass, which a bare launchd/systemd environment would not.
  service do
    run [opt_bin/"lastpass-ssh-agent", "start"]
    keep_alive true
    log_path var/"log/lastpass-ssh-agent.log"
    error_log_path var/"log/lastpass-ssh-agent.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      Log in to LastPass first, then check the setup:

        lpass login you@example.com
        lastpass-ssh-agent doctor

      Run it in the background (launchd on macOS, systemd --user on Linux):

        brew services start lastpass-ssh-agent

      It restarts at every login. Homebrew does not restart services on
      upgrade, so after `brew upgrade` the old binary keeps serving until you
      do:

        brew services restart lastpass-ssh-agent

      Do NOT use `sudo brew services`: a system daemon has no GUI session, so
      every confirmation fails closed and nothing is ever signed.

      On Linux, a --user service runs only while you have a session
      (`loginctl enable-linger "$USER"` keeps it up without one), and the
      default "tty" confirmation has no terminal. Set a helper in
      ~/.config/lastpass-ssh-agent/config.toml before starting it:

        confirm = "askpass"
        askpass = "/usr/bin/ssh-askpass"

      Point SSH at the agent. The socket path differs per platform, so ask:

        lastpass-ssh-agent env

      and put that path in ~/.ssh/config, remembering that IdentityAgent
      overrides SSH_AUTH_SOCK for the hosts it matches:

        Host *
            IdentityAgent "<the path printed above>"

      There is a dev track (`brew install --HEAD`), which builds from source
      and does not move forward on a plain `brew upgrade`. Switching either
      way is documented at:

        https://github.com/lexbrugman/lastpass-ssh-agent#following-the-dev-branch
    EOS
  end

  test do
    # A release install must report exactly the version the formula claims —
    # a mismatch there means the formula and the binary came from different
    # builds. A head install cannot: brew calls it HEAD-<sha> while the binary
    # describes itself against the newest release tag it can see, so check the
    # name instead. Decided from `version` rather than `build`, which is not
    # dependable in a test.
    expected = if version.to_s.start_with?("HEAD")
      "lastpass-ssh-agent"
    else
      version.to_s
    end
    assert_match expected, shell_output("#{bin}/lastpass-ssh-agent --version")
    # doctor exits nonzero without a LastPass login, but must still run
    assert_match "lpass", shell_output("#{bin}/lastpass-ssh-agent doctor 2>&1", 1)
  end
end
